# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Build v2dat for OpenWrt

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.20'

      - name: Build static binary
        run: |
          mkdir -p dist
          for arch in amd64 arm64 mipsle; do
            echo "Building for $arch..."
            CGO_ENABLED=0 GOOS=linux GOARCH=$arch go build -o dist/v2dat-linux-$arch ./cmd/v2dat
          done


    - name: Upload file to Artifacts
      uses: actions/upload-artifact@v3
      with:
        name: v2dat
        path: v2dat
  
